import type { Order } from '@/types';

export const mockOrders: Order[] = [
  {
    id: 'ORD001',
    ownerId: 'user1',
    customerName: 'Alice Johnson',
    customerPhone: '555-0101',
    deliveryAddress: '123 Maple St, Springfield',
    status: 'Shipped',
    createdAt: new Date('2023-10-26T10:00:00Z'),
    trackingId: 'track_1a2b3c',
    saleLink: '/sale/sale_abc',
  },
  {
    id: 'ORD002',
    ownerId: 'user1',
    customerName: 'Bob Smith',
    customerPhone: '555-0102',
    deliveryAddress: '456 Oak Ave, Springfield',
    status: 'Processing',
    createdAt: new Date('2023-10-25T14:30:00Z'),
    trackingId: 'track_4d5e6f',
    saleLink: '/sale/sale_def',
  },
  {
    id: 'ORD003',
    ownerId: 'user1',
    customerName: 'Charlie Brown',
    customerPhone: '555-0103',
    deliveryAddress: '789 Pine Ln, Springfield',
    status: 'Delivered',
    createdAt: new Date('2023-10-24T09:00:00Z'),
    trackingId: 'track_7g8h9i',
    saleLink: '/sale/sale_ghi',
  },
  {
    id: 'ORD004',
    ownerId: 'user1',
    customerName: 'Diana Prince',
    customerPhone: '555-0104',
    deliveryAddress: '101 Justice Rd, Metropolis',
    status: 'Pending',
    createdAt: new Date('2023-10-27T11:00:00Z'),
    trackingId: 'track_j1k2l3',
    saleLink: '/sale/sale_jkl',
  },
  {
    id: 'ORD005',
    ownerId: 'user1',
    customerName: undefined,
    status: 'Created',
    createdAt: new Date('2023-10-28T08:00:00Z'),
    trackingId: 'track_m4n5o6',
    saleLink: '/sale/sale_mno',
  },
  {
    id: 'ORD006',
    ownerId: 'user1',
    customerName: 'Eve Adams',
    customerPhone: '555-0105',
    deliveryAddress: '221B Baker St, London',
    status: 'Canceled',
    createdAt: new Date('2023-10-23T18:00:00Z'),
    trackingId: 'track_p7q8r9',
    saleLink: '/sale/sale_pqr',
  },
];
